env:
  missing: 4
  rescuers: 6
  trees: 8
  safe_zones: 4
  max_cycles: 300
  continuous_actions: false
  vision_radius: 0.2
train:
  active: false
  algorithm: "mappo" # "ppo" or "mappo" (CTDE)
  total_timesteps: 10000
  eval_freq: 1000
  batch_size: 2048
  n_epochs: 40
  seed: 0
  render_mode: null
eval:
  active: false
  games: 10
  render_mode: "human"
save_folder: "search_rescue_logs/"
tensorboard:
  active: false
  port: 6006
