env:
  victims: 12
  rescuers: 6
  trees: 8
  safe_zones: 4
  max_cycles: 300
  continuous_actions: false
  vision_radius: 0.4
train:
  active: false
  total_timesteps: 102400
  eval_freq: 500
  batch_size: 2048
  n_epochs: 20
  seed: 0
  render_mode: null
  learning_rate: 0.001
eval:
  active: false
  games: 10
  render_mode: "human"
save_folder: "search_rescue_logs/"
tensorboard:
  active: false
  port: 6006
  enabled: true  # Enable TensorBoard logging during train/eval
